version: '2'

services:
  mongo:
    image: 'mongo:3'
    container_name: 'MongoDB'
    ports:
      - 27017:27017
  web:
    build: .
    container_name: 'DataChanllenge'
    depends_on:
      - mongo
    ports:
      - 8000:8000
    environment:
      MONGO_URI: 'mongodb://mongo:27017'
